spring:
  application:
    name: dev
  profiles:
    active: dev
  datasource:
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:pagination;MODE=PostgreSQL;DB_CLOSE_DELAY=-1
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_default: false
        jdbc:
          lob:
            non_contextual_creation: true
  thymeleaf:
    cache: false
    mode: HTML
    prefix: classpath:/templates
  devtools:
    restart:
      additional-paths: src/main/resources/static/
management:
  endpoints:
    web:
      exposure:
        include: "*"

server:
  port: 8080